# frozen_string_literal: true

source "https://rubygems.org"

gem 'bcrypt'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'rake', require: false
gem 'rbs', require: false
gem 'steep', '>= 1.8.0.dev', require: false
gem 'rbs-inline', require: false
