D = Steep::Diagnostic

target :app do
  signature "sig"

  check "app.rb"

  library "json", "securerandom", "base64", "digest"

  configure_code_diagnostics do |hash|
    hash[D::Ruby::MethodDefinitionMissing] = :warning
  end
end
