module Isupipe
  class App < Sinatra::Base
    def self.db_conn: () -> Mysql2::Client
    def self.connect_db: () -> Mysql2::Client
    def self.db_transaction: () { (Mysql2::Client) -> untyped } -> untyped
    def self.verify_user_session!: () -> nil
    def self.decode_request_body: (untyped data_class) -> untyped
    def self.cast_as_integer: (String str) -> Integer
    def self.fill_livestream_response: (Mysql2::Client tx, Hash[Symbol, untyped] livestream_model) -> Hash[Symbol, untyped]
    def self.fill_livecomment_report_response: (Mysql2::Client tx, Hash[Symbol, untyped] report_model) -> Hash[Symbol, untyped]
    def self.fill_livecomment_response: (Mysql2::Client tx, Hash[Symbol, untyped] livecomment_model) -> Hash[Symbol, untyped]
    def self.fill_user_response: (Mysql2::Client tx, Hash[Symbol, Mysql2::row_value_type] user_model) -> Hash[Symbol, untyped]
    def self.fill_reaction_response: (Mysql2::Client tx, Hash[Symbol, Mysql2::row_value_type] reaction_model) -> Hash[Symbol, untyped]
  end
end
